import * as Reaction from "react-icons/fa";

export const iconNames = [
	<Reaction.FaSmile />,
	<Reaction.FaEllo />,
	<Reaction.FaGrimace />,
	<Reaction.FaGrinAlt />,
	<Reaction.FaGrinBeamSweat />,
	<Reaction.FaGrinBeam />,
	<Reaction.FaGrinHearts />,
	<Reaction.FaGrinSquintTears />,
	<Reaction.FaGrinSquint />,
	<Reaction.FaGrinStars />,
	<Reaction.FaGrinTears />,
	<Reaction.FaGrinTongueSquint />,
	<Reaction.FaGrinTongueWink />,
	<Reaction.FaGrinTongue />,
	<Reaction.FaGrinWink />,
	<Reaction.FaGrin />,
	<Reaction.FaMehRollingEyes />,
	<Reaction.FaMeh />,
	<Reaction.FaMehBlank />,
	<Reaction.FaSkull />,
	<Reaction.FaTired />,
	<Reaction.FaAngry />,
	<Reaction.FaSadCry />,
	<Reaction.FaSadTear />,
];
